image: python

stages:
    - test

before_script:
    - pip install tox

python34:
    image: python:3.4
    stage: test
    script: tox -e py34

python35:
    image: python:3.5
    stage: test
    script: tox -e py35

python36:
    image: python:3.6
    stage: test
    script: tox -e py36

python37:
    image: python:3.7-dev
    stage: test
    script: tox -e py37
