image: python

stages:
    - test

before_script:
    - pip install tox

python38:
    image: python:3.8
    stage: test
    script: tox -e py38

python39:
    image: python:3.9
    stage: test
    script: tox -e py39

python310:
    image: python:3.10
    stage: test
    script: tox -e py310
