dist: trusty
sudo: false

language: python

matrix:
    include:
        - python: 3.6
          env: TOXENV=py36
        - python: 3.5
          env: TOXENV=py35
        - python: 3.3
          env: TOXENV=py33
        - python: 3.0
          env: TOXENV=py30

install:
      - "pip install tox"

script:
      - "tox -e $TOXENV"
