dist: xenial
sudo: false

language: python

matrix:
    include:
        - python: 3.8
          env: TOXENV=py38
        - python: 3.9
          env: TOXENV=py39
        - python: 3.10
          env: TOXENV=py310

install:
      - "pip install tox"

script:
      - "tox -e $TOXENV"
